INSERT INTO filter_terms (type, term) VALUES
('blocklist', 'oscar 2026'),
('blocklist', 'oscar 2025'),
('blocklist', 'oscar reforça'),
('blocklist', 'estatueta'),
('blocklist', 'premiação de cinema'),
('blocklist', 'hollywood'),
('blocklist', 'wagner moura'),
('blocklist', 'globo de ouro'),
('blocklist', 'novela'),
('blocklist', 'série de tv'),
('blocklist', 'ozempic'),
('blocklist', 'semaglutida'),
('blocklist', 'pague menos'),
('blocklist', 'rede de farmácia'),
('blocklist', 'chá para emagrecer'),
('blocklist', 'limpar o organismo'),
('blocklist', 'imposto de renda'),
('blocklist', 'declaração do ir'),
('blocklist', 'esfaqueou'),
('blocklist', 'esfaqueia'),
('blocklist', 'esfaqueamento'),
('blocklist', 'atropelamento'),
('blocklist', 'zendaya'),
('blocklist', 'crashes a'),
('blocklist', 'wedding'),
('blocklist', 'las vegas wedding'),
('blocklist', 'romance de estreia'),
('blocklist', 'companhia das letras'),
('blocklist', 'portfólio de investimentos'),
('blocklist', 'renda fixa'),
('blocklist', 'airpods'),
('blocklist', 'apple anuncia'),
('blocklist', 'churrasco durante atestado'),
('blocklist', 'ética saúde'),
('blocklist', 'gestão hospitalar')
ON CONFLICT DO NOTHING;